import './globals.scss';
import { Inter } from 'next/font/google';
import { cookies } from 'next/headers';
import Link from 'next/link';
import { getUserBySessionToken } from '../database/users';
import { LogoutButton } from './components/LogoutButton';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type LayoutProps = {
  children: string;
};

export default async function RootLayout({ children }: LayoutProps) {
  // 1. get the session token from the cookie
  const cookieStore = cookies();
  const sessionToken = cookieStore.get('sessionToken');

  const user = !sessionToken?.value
    ? undefined
    : await getUserBySessionToken(sessionToken.value);
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <nav className={styles.navbar}>
            <ul>
              <li>
                <Link className={styles.home} href="/">
                  home
                </Link>{' '}
              </li>
              <li>
                <Link className={styles.products} href="/products">
                  products
                </Link>
              </li>
              <li>
                <Link
                  className={styles.profile}
                  href={`/profile/${user?.username}`}
                >
                  profile
                </Link>
              </li>

              {user ? (
                <>
                  <li>
                    <Link className={styles.profile} href="/wishlist">
                      Wishlist
                    </Link>
                  </li>
                  <div className={styles.username}>{user.username}</div>
                  <LogoutButton />
                </>
              ) : (
                <>
                  <li>
                    <Link className={styles.li} href="/auth/register">
                      register
                    </Link>
                  </li>
                  <li>
                    <Link className={styles.login} href="/auth/login">
                      login
                    </Link>
                  </li>
                </>
              )}

              <li>
                <Link className={styles.cart} href="/cart">
                  cart
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        {children}
        <footer>
          <section className={styles.footer}>
            <p>@Cozjy Skates</p>

            <div>
              <p> LinzerStraße 228</p>
              <br />
              <p>Vienna, Austria, 1230</p>
            </div>
            <div>
              <p>Phone: +43 699 2587482</p>
              <br />
              <p>Customer Support: +43 676 4468721</p>
            </div>

            <div>
              <p>PAYMENT METHODS:</p>
              <br />
              <p>Klarna</p>

              <br />
            </div>
          </section>
        </footer>
      </body>
    </html>
  );
}
