import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <nav className="nav">
          <Link className="link1" href="/">
            home
          </Link>{' '}
          <Link className="link3" href="/products">
            products
          </Link>
          <Link className="link2" href="/login">
            login
          </Link>
          <Link href="/cart">cart</Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
