import './globals.scss';
import { Inter } from 'next/font/google';
import Link from 'next/link';
import styles from './layout.module.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
type LayoutProps = {
  children: string;
};

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <header className={styles.header}>
          <nav className={styles.navbar}>
            <ul>
              <li>
                <Link className="link1" href="/">
                  home
                </Link>{' '}
              </li>
              <li>
                <Link className="link3" href="/products">
                  products
                </Link>
              </li>
              <li>
                <Link className="link2" href="/login">
                  login
                </Link>
              </li>
              <li>
                <Link className="link2" href="/register">
                  register
                </Link>
              </li>
              <li>
                <Link className="link2" href="/cart">
                  cart
                </Link>
              </li>
            </ul>
          </nav>
        </header>
        <footer>
          <section className={styles.footer}>
            <div>
              <p>Cozjy Skates</p>
              <p> LinzerStraße 228</p>
              <p>Vienna, Austria, 1230</p>
              <p>Phone: +43 699 2587482</p>

              <p>Customer Support: +43 676 4468721</p>
            </div>
            <br />

            <br />
            <div>
              {/* <input className="inputFooter" /> */}
              PAYMENT METHODS:
              <br />
            </div>
          </section>
        </footer>

        {children}
      </body>
    </html>
  );
}
